spring:
  profiles:
    active: dev

testrun:
  browser: chrome

service:
  configs:
    micro1:
      url: "http://micro1"
      port: "1000"
    micro2:
      url: "http://micro2"
      port: "2000"

---

spring:
  config.activate.on-profile: dev

testrun:
  name: dev

---

spring:
  config.activate.on-profile: int

testrun:
  name: int

---